CompileFlags:
  Add: [-std=c++20, -xc++, -Wall, -Wextra, -Werror, -Wconversion]
Diagnostics:
  ClangTidy:
    Add: '*'
    Remove: [abseil-*, altera-*, android-*, fuchsia-*, google-*, llvm*, modernize-use-trailing-return-type, zircon-*, readability-else-after-return, readability-static-accessed-through-instance, readability-avoid-const-params-in-decls, cppcoreguidelines-non-private-member-variables-in-classes, cppcoreguidelines-avoid-magic-numbers, misc-non-private-member-variables-in-classes]
